### ISSUE TITLE
PAC3 + Pointshop2 Conflict?

### ISSUE THREAD

**Issue by Hendrik2412** [Kamshak/Pointshop2#185]
Hey, I'm pretty new to Pac3 and Pointshop2, but im searching for a little bit of help.

I get Errors, when trying to create new Objects in the PAC editor (Hats etc.). When created, the accessoires are visable, but not in the Pointshop 2 preview.

<img width="504" alt="Pointshop2" src="https://user-images.githubusercontent.com/77275904/173803685-e5ae9025-60b2-491f-bb07-beea0e442c04.PNG">

**I get these Errors by PAC3:**

[pac3] addons/pac3/lua/pac3/editor/client/view.lua:177: attempt to call method 'GetDrawPosition' (a nil value)
    1. CalcDrag - addons/pac3/lua/pac3/editor/client/view.lua:177
        2. HUDPaint - addons/pac3/lua/pac3/editor/client/view.lua:402
            3. unknown - addons/pointshop2/lua/ps2/modules/pointshop2/hat/cl_dpointshoppacview.lua:264
            
I've already tried to reinstall. I also removed the installed Workshop Addons. Following Addons are still installed:

**PS2-Addons:**
- libk
- pac3
- pointshop2
- ps2-boosters
- ps2-drops
- ps2-gamble
- ps2-permaweaps

Not PS2 **dependent:**
- rayboard (Scoreboard-Addon)
- rayhud (HUD-Addon)
- raylibs
- ulx & ulib
- a mapvote plugin

Hope you can help me. :)

**Comment by Procustes** [comment]
did you manage to fix it?

**Comment by askrealcookie** [comment]
Hey @Procustes. The problem is wrong version of PAC3. In order to fix icons bug, you'd need to install older version of PAC3, then regenerate icons. You can find more detailed instructions along with link to correct version on our Discord(https://discord.gg/N9DmwwX). The second error(one that shows up in the console) is because of buggy implementation of embedded pac editor. You should make your outfits in single player, and then import them when you are creating new item in PS2.
